config/routes.rb
Rails.application.routes.draw do
 
  resources :contacts
  root 'sessions#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  def can_destroy?
    self.class.reflect_on_all_associations.all? do |assoc|
      [
        %w(restrict_with_error restrict_with_exception).exclude?(assoc.options[:dependent].to_s),
        (assoc.macro == :has_one  && self.send(assoc.name).nil?),
        (assoc.macro == :has_many && self.send(assoc.name).empty?)
      ].include?(true)
    end
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :customer
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :name, presence: true
    validates :firstname, presence: true
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
    validates :ext, numericality: true, presence: false
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :contact, :dependent => :restrict_with_error
    VALIDATE_POSTAL_REGEX = /\A[ABCEGHJKLMNPRSTVXY]{1}\d{1}[A-Z]{1}[ -]?\d{1}[A-Z]{1}\d{1}\z/
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    enum activityType: [:technologie, :alimentaire, :industriel, :divertissement, :autre]
    validates :adressPostalCode, format: {with: VALIDATE_POSTAL_REGEX}
    validates :name, presence: true
    validates :relationshipStart, presence: true
    validates :activityType, presence: true
    validates :infoEmail, presence: true, format: { with: VALID_EMAIL_REGEX }
    validates :adressApt, length: { maximum: 12 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
              format:     { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :logged_in_user, only: [ :edit, :update, :destroy]

  def new
    @contact = Contact.new
    @contact.customer_id = params[:customer_id]
    render 'new'
  end
  
  def edit
    @contact = Contact.find(params[:id])
  end

  def create
    @contact = Contact.new(contact_params)
    @customer = Customer.find_by(params[:id])
      if @contact.save
        flash[:success] = "Contact was successfully created."
        redirect_to customer_path(@customer.id)
      else
        render 'new'
      end
  end

  def update
      @customer = Customer.find_by(params[:id])
      if @contact.update_attributes(contact_params)
        flash[:success] = "Contact was successfully updated."
        redirect_to customer_path(@customer.id)
      else
        render 'edit'
      end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @customer = Customer.find_by(params[:id])
    @contact.destroy
    flash[:success] = "Contact was successfully deleted."
    redirect_to customer_path(@customer.id)
  end

  private

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to root_url
    end
  end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :firstname, :email, :tel, :ext, :customer_id)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]

  def new
    @customer = Customer.new
  end

  def index
    @customers = Customer.all
  end


  def show
    @customers = Customer.find(params[:id])
    @contacts = Contact.where("customer_id = ?", params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path
    else
      render 'new'
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update_attributes(customer_params)
      flash[:success] = "Customer updated"
      redirect_to customers_path
    else
      render 'edit'
    end
  end

  def destroy
    @customer = Customer.find(params[:id])

    if @customer.can_destroy?
      @customer.destroy
      flash[:success] = "Customer deleted"
    else
      flash[:danger] = "Customer can't be deleted because it has 1 or more contact"
    end
    redirect_to customers_path
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :relationshipStart, :adressCity,
                                 :adressPostalCode, :adressStreet, :adressApt, :activityType, :infoEmail)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to root_url
    end
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to customers_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
    end

    

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Precicom"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

      
    # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
    # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
    # Forgets a persistent session.
  def forget(user)
    user.forget
  end
  
    # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_error_messages.html.erb
<% if @contact.errors.any? %>
  <div id="error_explanation" class="col-12">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@contact.errors.count, "error") %>.
    </div>
    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/contacts/_form.html.erb
<div class="col-md-6">
  <%= form_for(@contact) do |c| %>
    <%= render 'error_messages' %>
    <div class="d-flex justify-content-start col-lg-6 col-12 d-lg-none">
      <%= link_to 'Back', customer_path(@contact.customer_id), :class => "custom-btn" %>
    </div>
    <%= c.label "Name" %>
    <%= c.text_field :name, class: 'form-control' %>

    <%= c.label "First Name" %>
    <%= c.text_field :firstname, class: 'form-control' %>

    <%= c.label "Email" %>
    <%= c.email_field :email, class: 'form-control' %>

    <%= c.label "Telephone" %>
    <%= c.telephone_field :tel, class: 'form-control' %>

    <%= c.label "Ext" %>
    <%= c.text_field :ext, class: 'form-control' %>
      
    <%= c.hidden_field :customer_id, class: 'form-control', value: @contact.customer_id  %>
    <div class="row">
      <div class="d-lg-flex justify-content-start col-lg-6 col-12 d-none">
        <%= link_to 'Back', customer_path(@contact.customer_id), :class => "custom-btn" %>
      </div>  
    <div div class="col-lg-6 col-12 mb-3"> 
      <%= c.submit "Save changes", class: "btn btn-primary " %>
    </div>
  <% end %>
</div>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>
<div class="row justify-content-center">
  <%= render 'form', contact: @contact %>
</div>

app/views/contacts/new.html.erb
<h1>Add Contact</h1>
<div class="row justify-content-center">
  <%= render 'form', contact: @contact %>
</div>

app/views/customers/_error_messages.html.erb
<% if @customer.errors.any? %>
  <div id="error_explanation"  class="col-12">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@customer.errors.count, "error") %>.
    </div>
    <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/_form.html.erb
<div class="col-12">

  <%= form_for(@customer, :html => {:class => 'row justify-content-end'}) do |c| %>
    <%= render 'error_messages' %>
    <div class="d-flex justify-content-start col-lg-6 col-12 d-lg-none">
      <%= link_to 'Back', customers_path, :class => "custom-btn"%>
    </div>
    <div class="col-lg-6 col-12">
      <%= c.label :name %>
        <%= c.text_field :name, class: 'form-control' %>
      </div>

      <div class="col-lg-6 col-12">
        <%= c.label "Start Date" %>
        <%= c.text_field :relationshipStart, class: 'datepicker' %>
      </div>

      <div class="col-lg-6 col-12">
        <%= c.label "City" %>
        <%= c.text_field :adressCity, class: 'form-control' %>
      </div>

      <div class="col-lg-6 col-12">
        <%= c.label "Postal Code" %>
        <%= c.text_field :adressPostalCode, class: 'form-control' %>
      </div>
      
      <div class="col-lg-6 col-12">
        <%= c.label "Street" %>
        <%= c.text_field :adressStreet, class: 'form-control' %>
      </div>

      <div class="col-lg-6 col-12">
        <%= c.label "Appartement" %>
        <%= c.text_field :adressApt, class: 'form-control' %>
      </div>

      <div class="col-lg-6 col-12">
        <%= c.label "Activity Type" %>
        <%= c.select :activityType, Customer.activityTypes.keys.map {|c| [c.humanize, c]} %>
      </div>

      <div class="col-lg-6 col-12"> 
        <%= c.label "Email" %>
        <%= c.email_field :infoEmail, class: 'form-control' %>
      </div>
      
      <div class="d-lg-flex justify-content-start col-lg-6 col-12 d-none">
          <%= link_to 'Back', customers_path, :class => "custom-btn"%>
      </div>
      <div class="col-lg-6 col-12 mb-3"> 
        <%= c.submit "Save changes", class: "btn btn-primary " %>
      </div>
    </div>
  <% end %>
</div>

app/views/customers/edit.html.erb
 <% provide(:title, "Edit customer") %>
 <h1>Editing Customer</h1>

  <%= render 'form', customer: @customer %>

app/views/customers/index.html.erb
<% provide(:title, 'All customers') %>
<h1>All customers</h1>
<div class="d-flex justify-content-end ">
  <%= link_to "Add", new_customer_path, :class => "custom-btn"%>
</div>
<table class="customers table table-responsive-lg">
  <tr>
    <th >Name</th>
    <th>Start date</th>
    <th>Activity Type</th>
    <th>Email</th>
    <th class="icon-link">Edit</th>
    <th class="icon-link">Delete</th>
  </tr>

<%  @customers.each do | customer | %>
  <tr>
    <td scope="row" class="uppercase">
      <%= link_to customer do %>
        <%= customer.name %>
      <% end %>
    </td>
    <td><%= customer.relationshipStart %></td>
    <td class="uppercase"><%= customer.activityType %></td>
    <td><%= customer.infoEmail %></td>
    <td class="icon-link">
      <%= link_to edit_customer_path(customer) do %>
        <%= fa_stacked_icon "edit"%>
      <% end %>
    </td>
    <td class="icon-link">
      <%= link_to customer, method: :delete, data: { confirm: "You sure?" } do %>
        <%= fa_stacked_icon "trash"%>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/customers/new.html.erb
 <% provide(:title, "New customer") %>
 <h1>Add customer</h1>

 <%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<div class="row">
  <section class="user_info col-12">
    <h1>
      <%= @customers.name %>
    </h1>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="customer-info-tab" data-toggle="tab" href="#customer-info" role="tab" aria-controls="customer-info" aria-selected="true">Info</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contacts</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active customer-info" id="customer-info" role="tabpanel" aria-labelledby="customer-info-tab">
        <div class="row">
          <p class="col-lg-6 col-12">Name: <span><%= @customers.name %></span></p>
          <p class="col-lg-6 col-12">Realationship Start: <span><%= @customers.relationshipStart %></span></p>
          <p class="col-lg-6 col-12">Activity Type: <span><%= @customers.activityType %></p>
          <p class="col-lg-6 col-12">Email: <span><%= @customers.infoEmail %></span></p>
          <p class="col-lg-6 col-12">City: <span><%= @customers.adressCity %></span></p>
          <p class="col-lg-6 col-12">Postal Code: <span><%= @customers.adressPostalCode %></span></p>
          <p class="col-lg-6 col-12">Street: <span><%= @customers.adressStreet %></span></p>
          <p class="col-lg-6 col-12">Apt.: <span><%= @customers.adressApt %></span></p>
        </div>
        <div class="d-flex justify-content-end">
          <%= link_to 'Back', customers_path, :class => "custom-btn "%>
        </div>
      </div>
      <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
        <div class="d-flex justify-content-end mt-2">
          <%= link_to "Add", new_contact_path(customer_id: @customers.id), :class => "custom-btn"%>
      </div>
      <div class="table-responsive-md">
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Firstname</th>
              <th>Email</th>
              <th>Telephone</th>
              <th>Ext</th>
              <th>Edit</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
            <% @contacts.each do |contact| %>
            <tr>
              <td><%= contact.name %></td>
              <td><%= contact.firstname %></td>
              <td><%= contact.email %></td>
              <td><%= contact.tel %></td>
              <td><%= contact.ext %></td>
              <td class="icon-link">
                <%= link_to edit_contact_path(contact, customer_id: @customers.id) do %>
                  <%= fa_stacked_icon "edit"%>
                <% end %>
              </td>
              <td class="icon-link">
                <%= link_to contact, method: :delete, data: { confirm: "You sure?" } do %>
                  <%= fa_stacked_icon "trash"%>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="d-flex justify-content-end">
        <%= link_to 'Back', customers_path, :class => "custom-btn"%>
      </div>
    </div>
  </section>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Home", customers_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
            <%= link_to "Log out", logout_path, method: :delete %>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">
  </head>
  <body>
  <% if logged_in? %>
    <%= render 'layouts/header' %>
    <% end %>
    <div class="container-website  position-relative">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> alert-dismissible fade fade-in show">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <%= yield %>
    </div>
    
  </body>
</html>